### ISSUE TITLE
Is it possible to simulate a drag event?

### ISSUE THREAD

**Issue by swese44** [screener-io/screener-storybook#106]
We're using `react-dnd` for a drag and drop feature. Does screener provide a way to simulate a drag event so we could get a screenshot of a drop target's active state (while mouse-dragging a file over the top)?

**Comment by loyalchow** [comment]
@swese44 you may be able to simulate by injecting a JS library like https://github.com/Photonios/JS-DragAndDrop-Simulator

I've created a simple example using this simulator and the react-dnd tutorial web site using screener-runner Steps:

https://gist.github.com/loyalchow/121fb4a2427f3db304b4316c44b10c1e

Hope that is helpful, cheers
