### ISSUE TITLE
-src-font-text-width causing changes when running screener

### ISSUE THREAD

**Issue by makopch-ms** [screener-io/screener-storybook#108]
We have noticed recently, at least with in the last two weeks, that people are getting failures in their screener runs because of the attribute '-src-font-text-width' changing causing false positives.  The component doesn't actually appear to change when using overlay.

We don't see this property on the elements in any of our environments (local storybook, official product releases, various demo pages), so is this something coming from how screener runs our stories and captures the images?

Is there a reason for the change?

**Comment by loyalchow** [comment]
@makopch-ms yes, this attribute is something Screener adds when performing its diff process. Can you provide a Screener URL to a component where you see this issue? And then we will investigate further, thanks

**Comment by makopch-ms** [comment]
Has an example of the failure:
https://screener.io/v2/states/rJkmevhuE.OC-office-online-ui/package-updater%2Fnpm-package-update-1591887861541/1920x1080/Chrome/appfontstylespreviewgallery-ribbonfontstylespreviewgallery-hovergallerybutton-0

Please let me know if you need a different link.

**Comment by loyalchow** [comment]
Thanks @makopch-ms - we've reviewed, and it's flagged as a visual change because the font is different. This can be seen using the Overlay slider - the font style visually changed. Hope this information is helpful

**Comment by makopch-ms** [comment]
@loyalchow so the change that was being made in the link that I sent, has no impact on those screenshots, the code effected a different component, no external dependencies were being updated.  So why did it change?  you said the -src-font-text-width is coming from screener, so how could our tests have an impact on that?

**Comment by loyalchow** [comment]
@makopch-ms Looking at the component screenshots, the font styles did visually change, so the -src-font is working correctly.

The question then is: why did the font change? If you haven't made any code changes that would impact the font changing, then the only thing I can think of is that the font file wasn't loaded yet in the browser when the screenshot was captured. Are you seeing this issue intermittently? As in, sometimes the font is sometime loaded and sometimes it's not?
