### ISSUE TITLE
[Security advistory] Move away from node-static 

### ISSUE THREAD

**Issue by MLoughry** [screener-io/screener-storybook#112]
Per [this advisory](https://www.npmjs.com/advisories/1208)

>Overview
All versions of node-static are vulnerable to a Denial of Service. The package fails to catch an exception when user input includes null bytes. This allows attackers to access http://host/%00 and crash the server.
>
>Remediation
No fix is currently available. Consider using an alternative package until a fix is made available.

Given that this advisory is considered high-severity, it causes issues for codebases that have strict audit requirements on their dependencies.

**Comment by loyalchow** [comment]
Thanks @MLoughry - we're looking into this, and should have a new release out soon with `node-static` removed as a dependency

**Comment by loyalchow** [comment]
@MLoughry Updated https://github.com/screener-io/screener-storybook/pull/113 and published `v0.20.1`
