### ISSUE TITLE
backdrop-filter blur not appearing in Screener screenshots

### ISSUE THREAD

**Issue by swese44** [screener-io/screener-storybook#117]
We're introducing a component which uses CSS rule `backdrop-filter: blur(16px)`. This works as expected in Chrome, but not in Screener when running against Chrome. Maybe Screener is running an older version of Puppeteer? It looks like support was added in Chrome 76: https://caniuse.com/css-backdrop-filter

Storybook on Chrome:
![Screen Shot 2020-10-21 at 4 44 48 PM](https://user-images.githubusercontent.com/471731/96801603-d435b100-13bc-11eb-9c0c-2ed74a13674a.png)

Screener:
![Screen Shot 2020-10-21 at 4 27 13 PM](https://user-images.githubusercontent.com/471731/96801610-d992fb80-13bc-11eb-97f0-f5eb958423ed.png)

**Comment by loyalchow** [comment]
@swese44 We are integrating with Sauce, and plan to update our default browser version - will keep you posted when available.

**Comment by loyalchow** [comment]
@swese44 Chrome has been updated to 87

**Comment by swese44** [comment]
Thanks @loyalchow!
