### ISSUE TITLE
Support web workers for msw-storybook-addon

### ISSUE THREAD

**Issue by igoldny** [screener-io/screener-storybook#125]
Hey, 
We are trying to integrate [msw-storybook-addon](https://github.com/mswjs/msw-storybook-addon) into our storybook.
but I don't seem to be working with screener-storybook, msw is using web workers to overwrite HTTP requests.
i suspect that web workers not working in screener-storybook, any idea how i can enable it?

**Comment by loyalchow** [comment]
@igoldny We've tried msw-storybook-addon with screener-storybook, and are able to successfully mock HTTP requests. Can you provide instructions on how to reproduce, and additional details on the issue you are seeing?
