### ISSUE TITLE
Support for React 17?

### ISSUE THREAD

**Issue by GiriB** [screener-io/screener-storybook#138]
We are moving our apps to React 17. Are there any plans to update this package to be compatible with React 17 as well? 

From the React 17 has not major breaking changes so hopefully this wont be a lot of effort. Maybe the package.json can just expand dependency of react as `^16.0.0 || ^17.0.0`

Thanks!

**Comment by makopch-ms** [comment]
@loyalchow Can you help here?

**Comment by luisVelasquezSauce** [comment]
Hi @GiriB @makopch-ms we are looking into this ATM. But will add should support for React 17.

**Comment by GiriB** [comment]
Hey @luisVelasquezSauce! Do we have an ETA for this work? That will help us plan work on our end too. Thanks!

**Comment by sunilsurana** [comment]
All our projects are using React 17 so we would like to stay consistent across everything. There are multiple benefits we gain by keeping react version same across repo.

**Comment by GiriB** [comment]
@luisVelasquezSauce +1 to what @sunilsurana said. I think since React 17 doesn't have any breaking API change since React 16, you may have not run into any issue while using them together. But even then, the right thing is to officially update the package.json to mention that screener-storybook can work with React 17 as well.

**Comment by luishernandezv** [comment]
Hi @GiriB @sunilsurana we have published a beta version [0.0.23-beta.1](https://www.npmjs.com/package/screener-storybook/v/0.23.0-beta.1) with the updated dependencies, please give it a try and let me know how it goes.

**Comment by sunilsurana** [comment]
Thank you @luishernandezv
