### ISSUE TITLE
Does @storybook/html support steps method for testing interaction?

### ISSUE THREAD

**Issue by richardjimenez52** [screener-io/screener-storybook#149]
Our storybook stories are built using @storybook/html but there is no example of using Steps method to interact with our components built on html- the only example are Vue, React, and Angular yet on the README it says "Get visual regression tests across your React, Vue, Angular or **HTML components** with no additional coding!"

**Comment by JBallin** [comment]
Storybook Interactions can be used instead. Note that you'll need to create a new story for each snapshot.

https://storybook.js.org/addons/@storybook/addon-interactions

**Comment by richardjimenez52** [comment]
@JBallin is there an example or snippet of interaction for html? Seems the that reference link has all the code snippet examples written in react when i select HTML as the framework.

**Comment by richardjimenez52** [comment]
> Storybook Interactions can be used instead. Note that you'll need to create a new story for each snapshot.
> 
> https://storybook.js.org/addons/@storybook/addon-interactions

@JBallin is there an example or snippet of interaction for html? Seems the that reference link has all the code snippet examples written in react when i select HTML as the framework.

**Comment by JBallin** [comment]
Not sure about examples, I would just try them out and see what works.
