### ISSUE TITLE
Cannot "go to the New Project Wizard"

### ISSUE THREAD

**Issue by fransbernhard** [screener-io/screener-storybook#22]
Maybe I'm stupid here, but gotten stuck at step 3 of you setup documentation (https://screener.io/v2/docs). 3.1 asks me to go to "New Project Wizard", the link leads me to the login page for Screener (https://screener.io/login/). I cannot login with my github or any of my emails - cause I don't have an account - and I cant find any alternative for creating an account. How can I proceed?

**Comment by loyalchow** [comment]
@fransbernhard Screener's Storybook visual testing is currently in closed beta. To get access, please sign-up for an early-access account at https://screener.io

We'll look out for your name, and will be in touch. Thanks!

**Comment by loyalchow** [comment]
@fransbernhard FYI: we've updated our login page to make this clearer
