### ISSUE TITLE
Add --verbose option to pipe output from start-storybook

### ISSUE THREAD

**Issue by MLoughry** [screener-io/screener-storybook#34]
I'm trying Screener out for the first time now, and there's no feedback from the process for the last several minutes since it spawned the Storybook process. Since none of Storybook's output is being piped to the console, I have no way to tell what's going on (or wrong).

**Comment by loyalchow** [comment]
Hi Michael, you can run Screener with the `--debug` option.

For example, with yarn:

```
$ yarn test-storybook -- --debug
```
