### ISSUE TITLE
Create an alpha version for  "@storybook/react": "^4.0.0-alpha.10"

### ISSUE THREAD

**Issue by nelsonomuto** [screener-io/screener-storybook#60]
# Goal 
- Stay up to date with storybooks development as they are moving pretty fast and have a slew of changes in v4

**Comment by loyalchow** [comment]
Thanks @nelsonomuto - `screener-storybook` already supports Storybook v4 alpha, and we have clients that use this version. However, this support was not explicit when viewing our code, so we have made an update to fix this: https://github.com/screener-io/screener-storybook/pull/65
