### ISSUE TITLE
Cross browser runs (IE, Safari, Firefox)

### ISSUE THREAD

**Issue by nelsonomuto** [screener-io/screener-storybook#67]
# Goal 
Be able to see screenershots for IE, Safari and Firefox, not just Chrome @loyalchow

**Comment by loyalchow** [comment]
Hi @nelsonomuto - `screener-storybook` can do cross-browser testing already. 

We provide Chrome, Firefox, IE11. More details here: https://screener.io/v2/docs/test-cross-browser

Safari is coming soon. And we provide integrations with [Sauce Labs](https://screener.io/v2/docs/sauce) and [BrowserStack](https://screener.io/v2/docs/browserstack) as well
