### ISSUE TITLE
Please add a "focus" step

### ISSUE THREAD

**Issue by swese44** [screener-io/screener-storybook#74]
I see hover, click, mousedown and mouseup. We also have styling for "focus" we'd like to have visual coverage for. thanks!

**Comment by loyalchow** [comment]
@swese44 We've added a new `focus` Step method in v0.15.0

FYI: it works by setting the cursor on the element you want to "focus" on. We've tried on text inputs, links and buttons.

**Comment by swese44** [comment]
awesome thank you!
