### ISSUE TITLE
Please add keyPress steps

### ISSUE THREAD

**Issue by swese44** [screener-io/screener-storybook#75]
Similar to hover/click etc, we need to be able to press up/down arrows, enter, characters, etc. for our visual tests. thanks

**Comment by loyalchow** [comment]
@swese44 a new `keys` Step method has been added in v0.15.0

It takes 2 arguments: a css selector for the element to send the keys to, and the set of keys.

We've also added a `Keys` property to the `Screener` tag, which exposes special keys, such as up/down arrows, enter key, etc.

Map of available keys can be found here: https://github.com/screener-io/screener-runner/blob/master/src/keys.js

Example:

```javascript
import Screener, {Steps, Keys} from 'screener-storybook/src/screener';

storiesOf('MyComponent', module)
  .add('default', () => (
    <Screener steps={new Steps()
    	.keys('input', Keys.enter)
    	.snapshot('click enter')
    	.end()
    }>
      <MyComponent />
    </Screener>
  ));```

**Comment by swese44** [comment]
awesome thanks!
