### ISSUE TITLE
Unable to use Keys.tab

### ISSUE THREAD

**Issue by swese44** [screener-io/screener-storybook#78]
Hello. This example causes the Screener run to error out on Chrome (other runs were canceled before other browsers were tested):

```typescript
    <Screener
      steps={new Steps()
        .cssAnimations(false)
        .click('.y-block')
        .snapshot('mouse mode')
        .keys('.y-block', Keys.tab)
        .snapshot('keyboard mode')
        .end()}
    >
      <KeyboardNavigationObserver
        renderInKeyboardMode={renderInKeyboardMode}
        renderInMouseMode={renderInMouseMode}
        onEnterKeyboardMode={action('entered keyboard mode')}
        onEnterMouseMode={action('entered mouse mode')}
      />
    </Screener>
```

it's sending a TAB key event to a div, is this not supported? i'm trying to test a component which toggles state when the user us navigating via keyboard vs. mouse. thanks!

**Comment by loyalchow** [comment]
@swese44 We are seeing the following chromedriver error associated with your test: `cannot focus element`

FYI: we have tested `tab` on text inputs and body element without issue.

Does the `tab` key need to be sent directly to the `.y-block` element? Or can it be sent to the body container?

**Comment by swese44** [comment]
Perfect, thanks! Might be good to add a note to the docs in case anyone else runs into it
