### ISSUE TITLE
IE11 seems to hover on random stories

### ISSUE THREAD

**Issue by swese44** [screener-io/screener-storybook#79]
Maybe the mouse position needs to be reset before each story? I see random stories rendering hover states only in IE11. Examples:

correct:
<img width="654" alt="screen shot 2018-10-07 at 10 28 40 pm" src="https://user-images.githubusercontent.com/471731/46593452-f2a00c80-ca80-11e8-9033-29a617a955e9.png">

correct:
<img width="654" alt="screen shot 2018-10-07 at 10 28 40 pm" src="https://user-images.githubusercontent.com/471731/46593456-f9c71a80-ca80-11e8-89bf-c6862c71bea4.png">

incorrect, showing hover state in both cases:
<img width="672" alt="screen shot 2018-10-07 at 10 28 53 pm" src="https://user-images.githubusercontent.com/471731/46593441-e1570000-ca80-11e8-8ba4-8d39cce3c162.png">
<img width="667" alt="screen shot 2018-10-07 at 10 38 08 pm" src="https://user-images.githubusercontent.com/471731/46593550-c8028380-ca81-11e8-8c28-dc75c3f4cde3.png">

Chrome showing the correct behavior:
<img width="665" alt="screen shot 2018-10-07 at 10 33 53 pm" src="https://user-images.githubusercontent.com/471731/46593479-2713c880-ca81-11e8-9baa-65eea02becaf.png">
<img width="675" alt="screen shot 2018-10-07 at 10 38 30 pm" src="https://user-images.githubusercontent.com/471731/46593552-cb960a80-ca81-11e8-9231-51a83af0fdf2.png">

**Comment by loyalchow** [comment]
@swese44 we're finding it difficult to reproduce; as you say, it appears a bit random.

As you suggested, we are now "resetting" the mouse when loading a new story in IE11. This has just been released.

**Comment by swese44** [comment]
looks like resetting fixes the issue, thanks for responding so quickly!
