### ISSUE TITLE
Add the ability to Support 3rd Party Libraries in Screener Steps

### ISSUE THREAD

**Issue by chang47** [screener-io/screener-storybook#99]
Hello, 

My team in the company I work for is happily using Screener for our UI regression testing where we wrote an extensive amount of tests to hover/click/focus/etc our components.

We want to be able to leverage our existing tests and integrate other 3rd party open source libraries into the steps that run.

A specific example is that we want to be able to run a popular accessibility tool called Axe during each snapshot to also scan for any accessibility violation. We were wondering if there is any support for this type of capability?

Thanks!

**Comment by loyalchow** [comment]
Hi @chang47 thanks for reaching out. Screener Steps does not currently support this.

Initial question: do you use the Storybook accessibility addon?
https://www.npmjs.com/package/@storybook/addon-a11y

**Comment by chang47** [comment]
Ooh, I was not aware that storybook had this addon, thank you for sharing.

One question regarding this:

It looks like the addon uses axe-core, which is awesome as that's the very library we want to use. Can Screener integrate with this addon? Specifically what I'm really interested in is leveraging our existing hover/click/focus tests that we are using screener

**Comment by loyalchow** [comment]
@chang47 the storybook a11y addon appears to add the axe-core library to Storybook stories. I have not tried this, but here is a potential idea that you could try: use the `executeScript` step in Screener to then run axe: `axe.run(...)`, and throw an exception when a violation is found to fail Screener test

**Comment by chang47** [comment]
@loyalchow Thanks, I'll play around with it and see if I can get a satisfactory answer.

**Comment by chang47** [comment]
@loyalchow Actually re-opening this for one last question.

I don't know much of the underlying implementation of screener, but whenever we run our tests, are the tests being ran on screener's service?

I ask, because even if we were to catch and throw an exception of the errors, I would like to be able to get the return data for us to visualize in our pipeline, which would be more helpful than throwing an error with text of our failures. 

Thank you!

**Comment by loyalchow** [comment]
@chang47 yes, Screener runs tests in browsers in the cloud, and then returns the success/fail result. So if you were to try the idea above, it would run in our cloud browser, not directly in your pipeline. Hope this information is helpful to you
